AWSTemplateFormatVersion: '2010-09-09'
Description: Central S3 logging bucket

Resources:
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "account-logs-${AWS::AccountId}"
      AccessControl: LogDeliveryWrite
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  LoggingBucketName:
    Value: !Ref LoggingBucket
    Export:
      Name: S3LoggingBucket