AWSTemplateFormatVersion: '2010-09-09'
Description: Test S3 Bucket in Prod Account

Resources:
  TestS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "github-actions-test-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
