name: Test Prod Deployment

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1

jobs:
  deploy-prod-test:
    name: Deploy Test Stack to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Prod)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole-production
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Test CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file infra/test-s3-prod.yaml \
            --stack-name github-actions-s3-test \
            --capabilities CAPABILITY_NAMED_IAM
