name: Test AWS OIDC
on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Print GitHub OIDC token
      run: |
        echo "TOKEN: $(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")"

    
    #- name: Configure AWS credentials
    #  uses: aws-actions/configure-aws-credentials@v2
    #  with:
    #    role-to-assume: arn:aws:iam::209479297458:role/GitHubActionsRole-production
    #    aws-region: ${{ env.AWS_REGION }}

    #- name: Test AWS access
    #  run: aws s3 ls
